[package]
name = "clopy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1"
flate2 = "1.0"
reqwest = { version = "0.11" }
tar = "0.4"
tokio = { version = "1", features = ["full"] }